name: CI Pipeline Check for Title

on:
  push:
    branches:
      - main # or the branch you want to trigger this pipeline on
  pull_request:
    branches:
      - main # trigger on PRs targeting the main branch

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the desired Node.js version

      - name: Run title tag check
        run: |
          chmod +x ./check-title.sh
          ./check-title.sh
          
      - name: Proceed with the pipeline (if title tag exists)
        if: success()  # This ensures the next step runs only if the previous step was successful
        run: |
          echo "Proceeding with the rest of the pipeline since the title tag exists."
          # Add additional steps here for further actions, e.g., building, testing, etc.
          
      - name: Abort pipeline (if title tag is missing)
        if: failure()  # This ensures this step runs only if the previous step failed
        run: |
          echo "Aborting pipeline because the title tag is missing from index.html."
