name: CI Pipeline

on:
  push:
    branches:
      - main # or the branch you want to trigger this pipeline on
  pull_request:
    branches:
      - main # trigger on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the desired Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test # This will run your Mocha tests

      # Optionally, you can add a step to upload test results if needed
